[package]
name = "mudbeam"
authors = ["widici"]
description = "A traceroute implementation in rust"
version = "0.1.0"
edition = "2021"

[dependencies]
dns-lookup = "2.0.2"
pnet = "0.33.0"
clap = { version = "4.3.4", features = ["derive"]}
